#!/usr/bin/env python3
"""
Generate Phaser Editor 2D scene artifacts from converted scene data.

This script reads `web/data/phaser_scene_data.json` (generated by convert_unity_to_phaser.py)
and produces Phaser Editor `.scene` and `.js` files so level designers can load
scenes in Phaser Editor for inspection.

Usage:

    python tools/convert_unity_to_phaser.py                    # run this first!
    python tools/export_phaser_editor_scenes.py                 # export all scenes
    python tools/export_phaser_editor_scenes.py --scene desert_cave
    python tools/export_phaser_editor_scenes.py --out web/data/editor

The script expects platform texture mappings in `web/data/unity_platform_textures.json`.
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "web" / "data"
PLATFORM_TEXTURES_PATH = DATA_DIR / "unity_platform_textures.json"
SCENES_JSON_PATH = DATA_DIR / "scenes.json"
PHASER_DATA_PATH = DATA_DIR / "phaser_scene_data.json"


@dataclass
class SceneConfig:
    key: str
    name: str
    unity_scene: Optional[str]
    background: Dict
    layers: List[Dict]
    spawn: Dict[str, float]
    unity_mapping: Dict[str, float]
    unity_platform_count: int
    platforms: List[Dict]


@dataclass
class UnityPlatform:
    prefab_asset: str
    x: float
    y: float
    z: float
    scale_x: float
    scale_y: float
    width: float
    height: float


class ExportError(RuntimeError):
    pass


def load_json(path: Path) -> Dict:
    if not path.exists():
        raise ExportError(f"Required file missing: {path}")
    try:
        with path.open(encoding="utf-8") as handle:
            return json.load(handle)
    except json.JSONDecodeError as exc:
        raise ExportError(f"Invalid JSON in {path}: {exc}") from exc


def load_scenes() -> Dict[str, SceneConfig]:
    data = load_json(SCENES_JSON_PATH)
    scenes: Dict[str, SceneConfig] = {}
    for key, config in (data.get("scenes") or {}).items():
        scenes[key] = SceneConfig(
            key=key,
            name=config.get("name") or key,
            unity_scene=config.get("unityScene"),
            background=config.get("background") or {},
            layers=config.get("background", {}).get("layers") or [],
            spawn=config.get("spawn") or {"x": 0, "y": 0},
            unity_mapping=config.get("unityMappingMargins") or {},
            unity_platform_count=config.get("unityPlatformCount") or 0,
            platforms=config.get("platforms") or [],
        )
    return scenes


def load_phaser_data() -> Dict[str, Dict]:
    """Load converted Phaser scene data."""
    data = load_json(PHASER_DATA_PATH)
    # Data is structured as {"scenes": {"scene_key": {...}, ...}}
    return data.get("scenes", {})


def load_platform_textures() -> Dict[str, Dict]:
    return load_json(PLATFORM_TEXTURES_PATH)


def ensure_output_dirs(base: Path) -> None:
    base.mkdir(parents=True, exist_ok=True)


def export_scene(
    scene: SceneConfig,
    phaser_data: Dict,
    platform_textures: Dict[str, Dict],
    output_dir: Path,
) -> Tuple[Path, Path]:
    """
    Export Phaser Editor scene files from converted data.

    Args:
        scene: Scene configuration
        phaser_data: Converted Phaser scene data (already in pixel coordinates)
        platform_textures: Platform texture mappings
        output_dir: Output directory for .scene and .js files
    """
    ensure_output_dirs(output_dir)
    scene_path = output_dir / f"{scene.key}.scene"
    js_path = output_dir / f"{scene.key}.js"

    display_list = build_display_list(scene, phaser_data, platform_textures)
    scene_json = {
        "id": str(uuid.uuid4()),
        "sceneType": "SCENE",
        "settings": {
            "preloadPackFiles": [],
            "createMethodName": "editorCreate",
            "sceneKey": scene.key,
        },
        "displayList": display_list,
        "plainObjects": [],
        "meta": {
            "app": "Phaser Editor - Scene Editor",
            "url": "https://phaser.io/editor",
            "contentType": "phasereditor2d.core.scene.SceneContentType",
            "version": 5,
        },
    }

    with scene_path.open("w", encoding="utf-8") as handle:
        json.dump(scene_json, handle, indent=2)
        handle.write("\n")

    js_code = generate_scene_js(scene)
    js_path.write_text(js_code, encoding="utf-8")
    return scene_path, js_path


def build_display_list(
    scene: SceneConfig,
    phaser_data: Optional[Dict],
    platform_textures: Dict[str, Dict],
) -> List[Dict]:
    """
    Build Phaser Editor display list from converted scene data.

    Args:
        scene: Scene configuration
        phaser_data: Converted Phaser scene data (already in pixel coordinates)
        platform_textures: Platform texture mappings
    """
    display_list: List[Dict] = []

    def add_image(texture_key: str, file_path: str, depth: int, width: float, height: float, y: float = 360.0) -> None:
        # Generate label from texture key
        label = texture_key.replace("-", "_")

        display_list.append(
            {
                "type": "Image",
                "id": str(uuid.uuid4()),
                "label": label,
                "texture": {
                    "key": texture_key
                },
                "x": 640.0,
                "y": y,
                "scaleX": 1.0,
                "scaleY": 1.0,
            }
        )

    background = scene.background or {}
    bg_key = background.get("key") or f"bg-{scene.key}"
    bg_file = background.get("file")
    display_width = background.get("displayWidth") or 1280
    display_height = background.get("displayHeight") or 720
    add_image(bg_key, bg_file or "", background.get("sortingOrder") or 0, display_width, display_height)

    for layer in scene.layers:
        layer_key = layer.get("key") or f"{bg_key}-{layer.get('file')}"
        layer_file = layer.get("file") or ""
        layer_width = layer.get("displayWidth") or display_width
        layer_height = layer.get("displayHeight") or display_height
        add_image(layer_key, layer_file, layer.get("sortingOrder") or 0, layer_width, layer_height)

    # Add platforms from converted Phaser data (already in pixel coordinates)
    if phaser_data:
        for platform in phaser_data.get("platforms", []):
            display_list.append(build_platform_entry(platform, platform_textures))

    return display_list


def build_platform_entry(platform: Dict, platform_textures: Dict[str, Dict]) -> Dict:
    """
    Build Phaser Editor platform entry from converted Phaser data.

    Note: Coordinates are already in Phaser pixel space (no conversion needed).
    """
    prefab = platform.get("prefab_asset") or ""
    texture_meta = platform_textures.get(prefab, {})
    texture_key = texture_meta.get("textureKey") or "unity-platform-generic"

    # Generate label from texture key
    label = texture_key.replace("-", "_")

    entry = {
        "type": "Image",  # Use Image instead of Sprite for Phaser Editor compatibility
        "id": str(uuid.uuid4()),
        "label": label,
        "texture": {
            "key": texture_key
        },
        "x": platform.get("x", 0.0),  # Already in Phaser pixels
        "y": platform.get("y", 0.0),  # Already in Phaser pixels (no negation)
        "scaleX": 1.0,
        "scaleY": 1.0,
    }
    return entry


def is_one_way(prefab_asset: str) -> bool:
    return "floating_" in (prefab_asset or "").lower()


def generate_scene_js(scene: SceneConfig) -> str:
    class_name = "".join([token.capitalize() for token in scene.key.replace("-", "_").split("_")])
    if not class_name.endswith("Scene"):
        class_name = f"{class_name}Scene"
    return textwrap.dedent(
        f"""\
        // Auto-generated by export_phaser_editor_scenes.py

        class {class_name} extends Phaser.Scene {{

          constructor() {{
            super("{scene.key}");
          }}

          editorCreate() {{
            this.events.emit("scene-awake");
          }}

          create() {{
            this.editorCreate();
          }}
        }}

        export default {class_name};
        """
    )


def parse_args(argv: Optional[Iterable[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Phaser Editor scene files from runtime JSON.")
    parser.add_argument("--scene", action="append", dest="scenes", help="Limit export to specific scene keys.")
    parser.add_argument("--out", type=Path, default=DATA_DIR / "editor", help="Output directory for .scene/.js files.")
    return parser.parse_args(argv)


def main(argv: Optional[Iterable[str]] = None) -> int:
    args = parse_args(argv)

    try:
        scenes = load_scenes()
        phaser_scenes = load_phaser_data()  # Dict[scene_key, phaser_data]
        platform_textures = load_platform_textures()
    except ExportError as exc:
        print(f"[export_phaser_editor_scenes] {exc}", file=sys.stderr)
        return 1

    requested = set(args.scenes or [])
    exported: List[Tuple[Path, Path]] = []

    for key, scene in scenes.items():
        if requested and key not in requested:
            continue
        if not scene.unity_scene:
            continue

        # Lookup converted Phaser data by scene key
        phaser_data = phaser_scenes.get(key)
        if not phaser_data:
            print(f"[WARN] No converted Phaser data for {key} ({scene.unity_scene})", file=sys.stderr)
            print(f"       Run: python3 tools/convert_unity_to_phaser.py", file=sys.stderr)
            continue

        paths = export_scene(scene, phaser_data, platform_textures, args.out)
        exported.append(paths)
        print(f"[OK] Exported {key} -> {paths[0].relative_to(REPO_ROOT)}, {paths[1].relative_to(REPO_ROOT)}")

    if not exported:
        print("[WARN] No scenes exported (check --scene filters or unityScene assignments).", file=sys.stderr)
        return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
